env: try to fix qcacld-3.0 under tc_alt_mode set to 0
this caused it:
../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/hif/src/ce/ce_main.c:2135:10: error: implicit conversion from enumeration type 'A_STATUS' to different enumeration type 'QDF_STATUS' [-Werror,-Wimplicit-enum-enum-cast]
 2135 |                 return A_ERROR;
      |                 ~~~~~~ ^~~~~~~
  CC      drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/hif/src/mp_dev.o
1 error generated.
make[4]: *** [../scripts/Makefile.build:364: drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/hif/src/ce/ce_main.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [../scripts/Makefile.build:667: drivers/staging/qcacld-3.0] Error 2
make[2]: *** [../scripts/Makefile.build:667: drivers/staging] Error 2
make[1]: *** [/home/runner/work/perf_neon-builder/perf_neon-builder/android_kernel_xiaomi_sm6150/Makefile:1240: drivers] Error 2
make[1]: Leaving directory '/home/runner/work/perf_neon-builder/perf_neon-builder/android_kernel_xiaomi_sm6150/out'
make: *** [Makefile:153: sub-make] Error 2

also silents llvm noise